name: Build & Test EmbeddedRTOSSimulator

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential python3
      - name: Build
        run: |
          cd FreeRTOS/FreeRTOS/Demo/EmbeddedRTOSSimulator
          make clean && make
      - name: Run test script
        run: |
          cd FreeRTOS/FreeRTOS/Demo/EmbeddedRTOSSimulator
          chmod +x test_embeddedrtossim.sh
          ./test_embeddedrtossim.sh